### ISSUE TITLE
Slice Range Out of Bounds on Invalid Name

### ISSUE THREAD

**Issue by husobee** [polera/gonameparts#2]
I noticed I started getting a runtime exception when a fed in an invalid name.  If you try to Parse "I am a Popsicle" as a name, you will be able to reproduce the exception.  It seems that line 135 (https://github.com/polera/gonameparts/blob/master/nameparts.go#L135) of nameparts.go needs to perform a simple validation to make sure the lnEnd isn't less than partmap["lnprefix"].  I have a PR that will reference this issue.

**Comment by polera** [comment]
Hi, thanks for contributing - please add a test for this to nameparts_test.go and we'll get this merged in.

**Comment by husobee** [comment]
Test has been added to make sure the Parse call doesn't panic with a name that begins with "I am" which is clearly a bad name.

The test passes in my pull request, and fails against master currently.  Thanks!

**Comment by polera** [comment]
Merged in your contribution and test, thanks!
